# OS IMAGE
FROM ubuntu:20.04

# DESCRIPTION 
LABEL description = "PHP-SQLITE3 DOCKER FILE"

# UPDATE PACKAGES
# INSTALL PHP 7.4 SERVER
RUN apt-get update && apt-get -y install software-properties-common && add-apt-repository ppa:ondrej/php && apt-get update && apt-get install -y apache2 && apt-get install -y php7.4 && apt-get install -y libapache2-mod-php7.4 php7.4-curl php7.4-json && apt-get clean && rm -rf /var/lib/apt/lists/*

# INSTALL SQLITE3
RUN apt update
RUN apt install sqlite3 -y

# INSTALL PHP-SQLITE3:
RUN apt-get install php7.4-sqlite -y

# OPEN DEFAULT PHP PORT
EXPOSE 80